import {firebaseConfig} from './firebase-config.js';
import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js';
import {getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js';
import {getFirestore,doc,setDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const $=id=>document.getElementById(id);let scanner=null,scanning=false;
function message(s){$('message').textContent=s}function tab(t){for(const x of ['receipt','scan','history'])$(x).hidden=x!==t;if(t==='history')history()}document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{stopCamera();tab(b.dataset.tab)});
$('login').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);$('password').value='';message('Συνδέθηκες.')}catch(e){message('Αποτυχία σύνδεσης: '+e.code)}};$('logout').onclick=()=>signOut(auth);onAuthStateChanged(auth,u=>{$('login-panel').hidden=!!u;$('main-panel').hidden=!u;$('identity').textContent=u?'Συνδεδεμένο':'';if(u)tab('receipt')});
function saveLocal(e){try{const a=JSON.parse(localStorage.getItem('bale-wms-history')||'[]');a.unshift(e);localStorage.setItem('bale-wms-history',JSON.stringify(a.slice(0,200)))}catch(_){}}
function history(){const a=JSON.parse(localStorage.getItem('bale-wms-history')||'[]');$('history-items').replaceChildren();for(const e of a){const x=document.createElement('article');x.textContent=`${e.time} · ${e.type==='RECEIPT'?'Παραλαβή':'Λύσιμο'} · ${e.label} · ${e.state}`;$('history-items').append(x)}}
async function send(type,payload,label){if(!auth.currentUser)throw Error('Δεν έχει γίνει σύνδεση');const event_id=crypto.randomUUID();const record={event_id,type,payload,created_at:serverTimestamp(),created_by:auth.currentUser.uid,status:'PENDING'};await setDoc(doc(db,'wms_events',event_id),record);saveLocal({time:new Date().toLocaleString('el-GR'),type,label,event_id,state:'Στάλθηκε στο Firebase · αναμονή PC'});return event_id}
$('receipt-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),supplier=String(f.get('supplier')||'').trim(),lot=String(f.get('lot')||'').trim(),total_kg=Number(f.get('total_kg')),quantity=Number(f.get('quantity'));if(!supplier||!Number.isSafeInteger(total_kg)||!Number.isSafeInteger(quantity)||quantity<1||quantity>10000||total_kg<quantity||total_kg>100000000){message('Έλεγξε προμηθευτή, κιλά και ποσότητα.');return}const b=e.target.querySelector('button');b.disabled=true;try{await send('RECEIPT',{supplier,lot,total_kg,quantity},`${supplier} · ${quantity} bales · ${total_kg} kg`);message('Η παραλαβή στάλθηκε. Οι κωδικοί BL θα δημιουργηθούν στο PC.');e.target.reset()}catch(err){message('Η αποστολή δεν επιβεβαιώθηκε. Μην την επαναλάβεις χωρίς έλεγχο: '+err.message)}finally{b.disabled=false}};
function codeFromQr(raw){const v=String(raw||'').trim().toUpperCase();const m=v.match(/BL-\d{8}/);return m?m[0]:null}function found(raw){const code=codeFromQr(raw);if(!code){$('camera-status').textContent='Το QR δεν περιέχει έγκυρο κωδικό BL.';return}$('bale-code').value=code;$('camera-status').textContent='Αναγνωρίστηκε: '+code;stopCamera()}
async function stopCamera(){if(scanner){try{if(scanning)await scanner.stop()}catch(_){}try{scanner.clear()}catch(_){}scanner=null}scanning=false;$('camera-stop').hidden=true}
$('camera-start').onclick=async()=>{if(!window.isSecureContext){$('camera-status').textContent='Η κάμερα απαιτεί HTTPS.';return}if(!window.Html5Qrcode){$('camera-status').textContent='Δεν φορτώθηκε η βιβλιοθήκη QR. Έλεγξε τη σύνδεση και ξαναφόρτωσε.';return}await stopCamera();try{scanner=new Html5Qrcode('qr-reader');await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:240,height:240}},found,()=>{});scanning=true;$('camera-stop').hidden=false;$('camera-status').textContent='Στόχευσε το QR στην ετικέτα.'}catch(e){$('camera-status').textContent='Η κάμερα δεν άνοιξε: '+e.message+' · Έλεγξε την άδεια κάμερας.';await stopCamera()}};$('camera-stop').onclick=stopCamera;
$('photo').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;if(!window.Html5Qrcode){$('camera-status').textContent='Η βιβλιοθήκη QR δεν φορτώθηκε.';return}await stopCamera();try{scanner=new Html5Qrcode('qr-reader');found(await scanner.scanFile(f,true))}catch(err){$('camera-status').textContent='Δεν αναγνωρίστηκε QR στη φωτογραφία: '+err.message}finally{await stopCamera();e.target.value=''}};
$('open-submit').onclick=async()=>{const code=codeFromQr($('bale-code').value);if(!code){message('Σκάναρε QR ή πληκτρολόγησε έγκυρο κωδικό BL-00000000.');return}const b=$('open-submit');b.disabled=true;try{await send('OPEN_BALE',{code},code);message('Το αίτημα ανοίγματος '+code+' στάλθηκε. Αναμένει επεξεργασία στο PC.');$('bale-code').value=''}catch(e){message('Δεν επιβεβαιώθηκε η αποστολή: '+e.message)}finally{b.disabled=false}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
